name: "Sample form 2"
description: "User Form to collect basic info"
title: "[User Data]: "
labels: ["Details", "User Info"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: input
    id: name
    attributes:
      label: Name
      description: "Enter your Full Name"
      placeholder: "ex. John Snow"
    validations:
      required: true
  - type: input
    id: mobile
    attributes:
      label: Mobile
      description: "Enter your mobile number"
      placeholder: "+12344556567"
      
    validations:
      required: true 
  - type: textarea
    id: query
    attributes:
      label: Query
      description: "Enter your query here."
     
